// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: native, powerpc-registered-target
// UNSUPPORTED: !powerpc64le-
// The stdlib.h included in mm_malloc.h references native system header
// like: bits/libc-header-start.h or features.h, cross-compile it may
// require installing target headers in build env, otherwise expecting
// failures. So this test will focus on native build only.

// RUN: %clang -target powerpc64le-unknown-linux-gnu -S -emit-llvm %s -fno-discard-value-names -mllvm -disable-llvm-optzns -o - | llvm-cxxfilt | FileCheck %s

#include <mm_malloc.h>


void __attribute__((noinline))
// CHECK-LABEL: @test_mm_malloc(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[BUF:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[CALL:%.*]] = call i8* @_mm_malloc(i64 noundef 100, i64 noundef 16)
// CHECK-NEXT:    store i8* [[CALL]], i8** [[BUF]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i8*, i8** [[BUF]], align 8
// CHECK-NEXT:    call void @_mm_free(i8* noundef [[TMP0]])
// CHECK-NEXT:    ret void
//
test_mm_malloc() {
  char *buf = _mm_malloc(100, 16);
  _mm_free(buf);
}



